apr:
  arch: apr apr-util
  cygwin: libapr1 libaprutil1
  debian: libapr1-dev libaprutil1-dev
  fedora: apr-devel apr-util
  freebsd: builtin
  gentoo: dev-libs/apr dev-libs/apr-util
  macports: apr apr-util
  opensuse: libapr1 libapr-util1
  rhel: apr-devel apr-util
  ubuntu: libapr1-dev libaprutil1-dev
assimp:
  debian:
    source: {md5sum: d5137302d8f00241ee10e623b97f9d22, uri: 'https://kforge.ros.org/rosrelease/viewvc/sourcedeps/assimp/assimp-2.0.86-1.rdmanifest'}
  ubuntu:
    apt:
      packages: [assimp-dev]
atlas:
  arch: ''
  debian: libatlas-base-dev
  fedora: atlas-devel
  gentoo: atlas
  macports: atlas
  ubuntu: libatlas-base-dev
autoconf:
  arch: autoconf
  debian: autoconf
  fedora: autoconf
  freebsd: autoconf213 autoconf268
  gentoo: sys-devel/autoconf
  macports: autoconf
  opensuse: autoconf
  rhel: autoconf
  ubuntu: autoconf
automake:
  arch: automake
  debian: automake
  fedora: automake
  freebsd: automake14 automake111
  gentoo: sys-devel/automake
  macports: automake
  opensuse: automake
  rhel: automake
  ubuntu: automake
bazaar:
  debian: bzr
  fedora: bazaar
  freebsd: bazaar
  gentoo: dev-vcs/bzr
  macports: bazaar
  opensuse: bzr
  ubuntu: bzr
bison:
  ubuntu: bison
  debian: bison
  macports: bison
boost:
  arch: boost
  cygwin: libboost-devel libboost1.40
  debian: {lenny: "if [ ! -f /opt/ros/lib/libboost_date_time-gcc43-mt*-1_37.a ] ;\
      \ then\n  mkdir -p ~/ros/ros-deps\n  cd ~/ros/ros-deps\n  wget --tries=10 http://pr.willowgarage.com/downloads/boost_1_37_0.tar.gz\n\
      \  tar xzf boost_1_37_0.tar.gz\n  cd boost_1_37_0\n  ./configure --prefix=/opt/ros\n\
      \  make\n  sudo make install\nfi\n", squeeze: libboost1.42-all-dev}
  fedora: boost-devel
  freebsd: boost-python-libs
  gentoo: dev-libs/boost
  macports: boost
  opensuse: boost-devel
  rhel: boost-devel
  ubuntu:
    lucid:
      apt:
        packages: [libboost1.40-all-dev]
    maverick:
      apt:
        packages: [libboost1.42-all-dev]
    natty:
      apt:
        packages: [libboost1.42-all-dev]
    oneiric:
      apt:
        packages: [libboost1.46-all-dev]
bzip2:
  arch: bzip2
  cygwin: bzip2
  debian: libbz2-dev
  fedora: bzip2-devel
  freebsd: bzip2
  gentoo: app-arch/bzip2
  macports: bzip2
  opensuse: libbz2-devel
  rhel: bzip2-devel
  ubuntu: libbz2-dev
checkinstall:
  debian:
    apt:
      packages: [checkinstall]
  ubuntu:
    apt:
      packages: [checkinstall]
cmake:
  ubuntu: cmake
cppunit:
  arch: cppunit
  debian: libcppunit-dev
  fedora: cppunit-devel
  freebsd: cppunit
  gentoo: dev-util/cppunit
  macports: cppunit
  opensuse: libcppunit-devel
  rhel: cppunit-devel
  ubuntu: libcppunit-dev
curl:
  arch: curl
  debian: libcurl4-openssl-dev
  fedora: libcurl-devel
  freebsd: curl
  gentoo: net-misc/curl
  macports: curl
  opensuse: libcurl-devel
  ubuntu: libcurl4-openssl-dev
doxygen:
  arch: doxygen
  debian: doxygen
  fedora: doxygen
  freebsd: doxygen
  gentoo: app-doc/doxygen
  macports: doxygen
  rhel: doxygen
  ubuntu: doxygen
eigen:
  debian:
    source: {md5sum: 941db2fbb09d80c28426d335022fad95, uri: 'https://kforge.ros.org/rosrelease/viewvc/sourcedeps/eigen/eigen-3.0.1-1.rdmanifest'}
  gentoo: '>=dev-cpp/eigen-3'
  ubuntu:
    apt:
      packages: [libeigen3-dev]
epydoc:
  debian: python-epydoc
  fedora: epydoc
  freebsd: epydoc
  gentoo: dev-python/epydoc
  macports: py26-epydoc
  ubuntu: python-epydoc
festival: {arch: festival festival-kallpc16k, debian: festival festvox-kallpc16k,
  ubuntu: festival festvox-kallpc16k}
ffmpeg:
  ubuntu: libavcodec-dev libavformat-dev libavutil-dev libswscale-dev
  debian: libavcodec-dev libavformat-dev libavutil-dev libswscale-dev
  macports: ffmpeg
  arch: ffmpeg
  gentoo: ffmpeg
  fedora: ffmpeg-devel
flex:
  ubuntu: flex
  debian: flex
  macports: flex
fltk:
  arch: fltk
  debian: libfltk1.1-dev
  fedora: fltk-devel
  freebsd: fltk
  gentoo: =x11-libs/fltk-1*
  macports: fltk
  opensuse: fltk-devel
  ubuntu: libfltk1.1-dev
freeimage:
  ubuntu: libfreeimage-dev
  macports: freeimage
  debian: libfreeimage-dev
  arch: freeimage
  gentoo: freeimage
  fedora: freeimage-devel
glut:
  ubuntu: 
    lucid: 
      apt:
        packages: [ libglut3-dev ]
    maverick: 
      apt:
        packages: [ libglut3-dev ]
    natty: 
      apt:
        packages: [ libglut3-dev ]
    oneiric:
      apt:
        packages: [ freeglut3-dev ]
  debian: libglut3-dev
  fedora: freeglut-devel
  arch: freeglut
  gentoo: freeglut
  macports: mesa
git:
  debian: git-core
  fedora: git
  freebsd: git
  gentoo: dev-vcs/git
  macports: git-core
  opensuse: git-core
  ubuntu: git-core
graphicsmagick:
  arch: graphicsmagick
  debian: libgraphicsmagick++1-dev
  gentoo: imagemagick
  macports: GraphicsMagick
  ubuntu: libgraphicsmagick++1-dev
  fedora: GraphicsMagick-c++-devel
graphviz:
  arch: graphviz
  debian: graphviz
  fedora: graphviz
  freebsd: graphviz
  gentoo: media-gfx/graphviz
  macports: graphviz
  opensuse: graphviz
  rhel: graphviz
  ubuntu: graphviz
gtest:
  debian: libgtest-dev
  fedora: gtest-devel
  freebsd: googletest
  gentoo: dev-util/gtest
  macports: google-test
  opensuse: gtest-devel
  ubuntu: libgtest-dev
gtk2:
  arch: gtk2
  debian: libgtk2.0-dev
  fedora: gtk2-devel
  freebsd: gtk20
  gentoo: x11-libs/gtk+
  macports: gtk2
  opensuse: gtk2-devel
  rhel: gtk2-devel
  ubuntu: libgtk2.0-dev
intltool:
  ubuntu: intltool
  opensuse: intltool 
  fedora: intltool
  gentoo: dev-util/intltool
  freebsd: intltool
jasper:
  ubuntu: libjasper-dev
  debian: libjasper-dev
  macports: jasper
  arch: jasper
  gentoo: jasper
  fedora: jasper-devel
libann-dev:
  ubuntu: libann-dev
libdevil-dev:
  ubuntu: libdevil-dev
libftgl-dev:
  ubuntu: libftgl-dev
libglew-dev:
  ubuntu: libglew1.5-dev
libglui-dev:
  ubuntu: libglui-dev
libgphoto-dev:
  ubuntu: libgphoto2-2-dev
libleptonica-dev:
  ubuntu: libleptonica-dev
libswscale-dev:
  ubuntu: libswscale-dev
libusb-1.0-dev:
  ubuntu: libusb-1.0-0-dev
libraw1394-dev:
  ubuntu:
    apt:
      packages: [libraw1394-dev]
  fedora:
    yum:
      packages: [libraw1394-devel]
libdc1394-dev:
  ubuntu:
    apt: 
      packages: [libdc1394-22-dev]
  arch:
    pacman:
      packages: [libdc1394]
  fedora:
    yum:
      packages: [libdc1394-devel]
  osx:
    macports:
      packages: [libdc1394]
libstdc++5:
  ubuntu: libstdc++5
  debian: libstdc++5
  opensuse: libstdc++33 
  freebsd: builtin
libtool:
  ubuntu:
    apt: 
      packages: [libtool, libltdl-dev]
  debian:
    squeeze: libtool libltdl-dev
    lenny: libtool libltdl3-dev
  opensuse: libtool libltdl3
  fedora: libtool libtool-ltdl-devel
  rhel: libtool libtool-ltdl-devel
  macports: libtool
  arch: libtool
  gentoo: sys-devel/libtool
  freebsd: libtool
libxaw:
  arch: libxaw
  debian: libxaw7-dev
  fedora: libXaw-devel
  freebsd: libXaw
  gentoo: x11-libs/libXaw
  macports: xorg-libXaw
  opensuse: xorg-x11-devel
  rhel: libXaw-devel
  ubuntu: libxaw7-dev
libxext:
  arch: libxext
  debian: libxext-dev
  fedora: libXext-devel
  freebsd: libXext
  gentoo: x11-libs/libXext
  macports: xorg-libXext
  opensuse: xorg-x11-libXext-devel
  rhel: libXext-devel
  ubuntu: libxext-dev
libxml2:
  arch: libxml2
  debian: libxml2-dev
  fedora: libxml2-devel
  freebsd: libxml2
  gentoo: dev-libs/libxml2
  macports: libxml2
  opensuse: libxml2-devel
  ubuntu: libxml2-dev
libxxf86vm:
  arch: libxxf86vm
  debian: libxxf86vm-dev
  fedora: libXxf86vm-devel
  freebsd: libXxf86vm
  gentoo: x11-libs/libXxf86vm
  macports: xorg-libXxf86vm
  opensuse: xorg-x11-devel
  rhel: libXxf86vm-devel
  ubuntu: libxxf86vm-dev
libjpeg:
  ubuntu: libjpeg62-dev
  debian: libjpeg62-dev
  fedora: libjpeg-devel
  macports: jpeg
  arch: libjpeg
libogg:
  ubuntu: libogg-dev
  debian: libogg-dev
  fedora: libogg-devel
  macports: libogg
  gentoo: media-libs/libogg
libpcap:
  ubuntu:
    apt:
      packages: [libpcap0.8-dev]
  debian:
    apt:
      packages: [libpcap0.8-dev]
  fedora:
    yum:
      packages: [libpcap-devel]
  osx:
    macports:
      packages: [libpcap]
  arch:
    pacman:
      packages: [libpcap]
libpq-dev:
  ubuntu: libpq-dev
libtheora:
  ubuntu: libtheora-dev
  debian: libtheora-dev
  fedora: libtheora-devel
  macports: libtheora
  gentoo: media-libs/libtheora
libqhull:
  ubuntu: libqhull-dev
  debian: libqhull-dev
  fedora: qhull-devel
  macports: qhull
libusb:
  ubuntu: libusb-1.0-0-dev
libvtk:
  ubuntu: libvtk5-dev
  debian: libvtk5-dev
  fedora: vtk-devel
  macports: vtk-devel
libx11:
  ubuntu: libx11-dev
  debian: libx11-dev
  fedora: libX11-devel
  macports: xorg-libX11
libxrandr:
  ubuntu: libxrandr-dev
  debian: libxrandr-dev
  arch: libxrandr
  gentoo: x11-libs/libXrandr
  macports: xorg-libXrandr
  fedora: libXrandr-devel
log4cxx:
  arch: 'if ! pacman -Q log4cxx; then yaourt -S log4cxx; fi

    '
  cygwin: liblog4cxx-devel
  debian: {lenny: "if [ ! -f /opt/ros/lib/liblog4cxx.so.10 ] ; then\n  mkdir -p ~/ros/ros-deps\n\
      \  cd ~/ros/ros-deps\n  wget --tries=10 http://pr.willowgarage.com/downloads/apache-log4cxx-0.10.0-wg_patched.tar.gz\n\
      \  tar xzf apache-log4cxx-0.10.0-wg_patched.tar.gz\n  cd apache-log4cxx-0.10.0\n\
      \  ./configure --prefix=/opt/ros\n  make\n  sudo make install\nfi\n", squeeze: liblog4cxx10-dev}
  fedora: log4cxx-devel
  freebsd: log4cxx
  gentoo: dev-libs/log4cxx
  macports: log4cxx
  opensuse: log4cxx-devel
  rhel: log4cxx-devel
  ubuntu: liblog4cxx10-dev
mercurial:
  debian: mercurial
  fedora: mercurial
  freebsd: mercurial
  gentoo: dev-vcs/mercurial
  macports: mercurial
  opensuse: mercurial
  ubuntu: mercurial
nvidia-cg:
  ubuntu: nvidia-cg-toolkit
  debian: nvidia-cg-toolkit
  fedora: Cg
  arch: |
    if ! pacman -Q nvidia-cg-toolkit ; then yaourt -S nvidia-cg-toolkit; fi
  gentoo: nvidia-cg-toolkit
  debian: nvidia-cg-toolkit
opengl:
  arch: mesa
  debian: libgl1-mesa-dev libglu1-mesa-dev
  fedora: mesa-libGL-devel mesa-libGLU-devel
  freebsd: mesagl-mangled
  gentoo: media-libs/mesa
  macports: mesa
  opensuse: Mesa-devel
  rhel: mesa-libGL-devel mesa-libGLU-devel
  ubuntu: libgl1-mesa-dev libglu1-mesa-dev
netpbm:
  ubuntu: libnetpbm10-dev
  debian: libnetpbm10-dev
  arch: netpbm
  macports: netpbm
  fedora: netpbm-devel
  gentoo: netpbm
pcre-dev:
  ubuntu: libpcre++-dev
  fedora: pcre-devel
pcre:
  ubuntu: libpcre3-dev
  fedora: pcre-devel
  debian: libpcre3-dev
pkg-config:
  arch: pkg-config
  cygwin: pkg-config
  debian: pkg-config
  fedora: pkgconfig
  freebsd: pkg-config
  gentoo: dev-util/pkgconfig
  macports: pkgconfig
  opensuse: pkg-config
  rhel: pkgconfig
  ubuntu: pkg-config
protobuf:
  ubuntu:
    oneiric: libprotobuf7
libqt4-dev:
  ubuntu: libqt4-dev
  arch: qt
  debian: libqt4-dev
  fedora: qt-devel
  freebsd: qt4-corelib
  gentoo: '>=x11-libs/qt-core-4'
  macports: qt4-mac
  opensuse: libqt4-devel
  ubuntu: libqt4-dev
libqt4-opengl-dev:
  ubuntu: libqt4-opengl-dev
qt4-qmake:
  ubuntu: qt4-qmake
readline-dev:
  ubuntu: libreadline-dev
  fedora: readline-devel
scons:
  arch: scons
  debian: scons
  fedora: scons
  freebsd: scons
  gentoo: dev-util/scons
  macports: scons
  opensuse: scons
  ubuntu: scons
sdl-image:
  ubuntu: libsdl-image1.2-dev
  debian: libsdl-image1.2-dev
  fedora: SDL_image-devel
  arch: sdl_image
  macports: libsdl_image
  gentoo: sdl-image
subversion:
  debian: subversion
  fedora: subversion
  freebsd: subversion
  gentoo: dev-vcs/subversion
  macports: subversion
  opensuse: subversion
  ubuntu: subversion
suitesparse:
  ubuntu: libsuitesparse-dev
tinyxml:
  debian: libtinyxml-dev
  fedora: tinyxml-devel
  ubuntu: libtinyxml-dev
tbb:
  ubuntu: libtbb-dev
tcsh:
  ubuntu: tcsh
  fedora: tcsh
uuid:
  ubuntu: uuid-dev
  debian: uuid-dev
  fedora: libuuid-devel
  macports: ossp-uuid
unzip:
  arch: unzip
  debian: unzip
  fedora: unzip
  freebsd: unzip
  gentoo: app-arch/unzip
  macports: unzip
  opensuse: unzip
  rhel: unzip
  ubuntu: unzip
wxpython:
  arch: wxpython
  centos: wxPython-devel
  debian: python-wxgtk2.8
  fedora: wxPython-devel
  freebsd: py27-wxPython
  gentoo: dev-python/wxpython
  macports: py26-wxpython py26-gobject py26-gtk py26-cairo
  opensuse: python-wxGTK
  rhel: wxPython-devel
  ubuntu: python-wxgtk2.8
wxwidgets:
  arch: wxgtk
  debian: libwxgtk2.8-dev
  fedora: wxGTK-devel
  freebsd: wxgtk2
  gentoo: x11-libs/wxGTK
  macports: wxWidgets-python
  opensuse: wxGTK-devel
  rhel: wxGTK-devel
  ubuntu: libwxgtk2.8-dev
xulrunner-dev:
  ubuntu: libv8-dev
  fedora: libv8-devel
yaml:
  fedora: libyaml-devel
  ubuntu: libyaml-dev
yaml-cpp:
  debian:
    source: {md5sum: f7fb81fd4a2fbd5022daa7686e816359, uri: 'https://kforge.ros.org/rosrelease/viewvc/sourcedeps/yaml-cpp/yaml-cpp-0.2.5.rdmanifest'}
  ubuntu:
    apt:
      packages: [yaml-cpp0.2.6-dev]
zlib:
  arch: zlib
  cygwin: zlib
  debian: zlib1g-dev
  fedora: zlib-devel
  freebsd: builtin
  gentoo: sys-libs/zlib
  macports: zlib
  opensuse: zlib-devel
  rhel: zlib-devel
  ubuntu: zlib1g-dev
zziplib:
  arch: zziplib
  debian: libzzip-0-13 libzzip-dev
  fedora: zziplib-devel
  freebsd: zziplib
  gentoo: dev-libs/zziplib
  macports: libzzip
  opensuse: zziplib-devel
  rhel: zziplib-devel
  ubuntu: libzzip-0-13 libzzip-dev
liblapack:
  debian: liblapack-dev
  fedora: lapack-devel
  ubuntu: liblapack-dev
