name: Add a distribution cache for each release
on:
  workflow_dispatch:
    inputs:
      distribution:
        description: 'The distribution key'
        required: true
        default: 'rolling'
        type: string
      release_tag:
        description: 'The release tag for the distribution'
        required: true
        default: '2025-09-05'
        type: string
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.distribution }}/${{ inputs.release_tag }}
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install locales
          sudo locale-gen en_US en_US.UTF-8
          sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
          export LANG=en_US.UTF-8
          sudo apt install software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install curl -y
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get update -qq
          sudo apt-get install -y python3-rosdistro
      - name: Regenerate cache
        run: |
          cd ${{ inputs.distribution }}
          rosdistro_build_cache ../index-v4.yaml ${{ inputs.distribution }}
          mv ${{ inputs.distribution }}-cache.yaml.gz ..
          cd ..
      - name: Replace index cache entry
        run: |
          export OLD_URL="http://repo.ros2.org/rosdistro_cache/${{ inputs.distribution }}-cache.yaml.gz"
          export NEW_URL="https://github.com/asymingt/rosdistro/releases/download/${{ inputs.distribution }}/${{ inputs.release_tag }}/${{ inputs.distribution }}-cache.yaml.gz"
          sed -i "s|${OLD_URL}|${NEW_URL}|g" index-v4.yaml
      - name: Push release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.distribution }}/${{ inputs.release_tag }}
          files: |
            ${{ inputs.distribution }}-cache.yaml.gz
            index-v4.yaml