name: 'Label inactive PRs as stale'

on:
  schedule:
    - cron: '0 11 * * *'  # runs at 11am UTC every day => early morning in US

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-pr-label: 'stale'
          stale-pr-message: "This PR is being marked as stale because there hasn't been activity in 14 days. It may be closed by a rosdistro maintainer. If this label isn't appropriate, you can remove the label and add the \"don't mark as stale\" label. You can find our community contributing guidelines here: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md."
          days-before-pr-stale: 14
          days-before-pr-close: -1     # dont close PRs automatically
          days-before-issue-stale: -1  # dont mark issues as stale
          days-before-issue-close: -1  # dont close issues automatically
          exempt-pr-labels: "don't mark as stale"
